languageCode = "en-us"
title = "SeisMan"
baseurl = "http://example.org/"

[params]
  name = "SeisMan"
  about = "Dongdong Tian &nbsp;&bull;&nbsp; USTC &nbsp;&bull;&nbsp; Seismologist"
  copyright = "SeisMan 2013-2018"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "false"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Academic"
  icon = "university"
  link = "http://home.ustc.edu.cn/~dongzhi"

[[params.social]]
  medium = "Blog"
  icon = "edit"
  link = "http://blog.seisman.info"

[[params.social]]
  medium = "Wiki"
  icon = "wikipedia-w"
  link = "http://wiki.seisman.info"

[[params.social]]
  medium = "Link"
  icon = "link"
  link = "http://blog.seisman.info/links/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/seisman"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:seisman.info@gmail.com"
